### ISSUE TITLE
NPC disappear

### ISSUE THREAD

**Issue by COPCHANNELTH** [Shopkeepers/Shopkeepers#481]
Plz.Help
my npc has disappear and I cannot fix it.

**Comment by blablubbabc** [comment]
I need more information in order to help you.
* What type of shopkeeper is disappearing? All or some specific?
* When is it disappearing? Will it disappear under a specific condition/event? Will it reappear again later/after reloads?
* Is the shopkeeper still listed inside the save.yml file, after it disappeared?
* Have you tried with a fresh spigot server and no other plugins? Most commonly, some other plugin is removing the shopkeeper or preventing it from being spawned. Try to find out which of your plugins might causing this issue.
* How can I reproduce this issue on my testing server?

**Comment by COPCHANNELTH** [comment]
@blablubbabc 

- All of shopkeeper is disappearing.
- It disappearing on loy krathong festival day.
- (I will go to ask my CEO server)
- (I will go to ask my CEO server)
-I DON'T know how to do that.

**Comment by COPCHANNELTH** [comment]
Thx I can fix it now

**Comment by blablubbabc** [comment]
Have you solved your issue? What was it caused by? (in case someone else runs into a similar issue)
