### ISSUE TITLE
All shops got whiped, no errors.

### ISSUE THREAD

**Issue by MithrandirCraft** [Shopkeepers/Shopkeepers#485]
Hello. This has happened to me once before in the past. The yml data has been misteriously reset.
What happened was: Afer the usual 8A.M Factions restart, all shops did not spawn. Some players found out, and savaged some of the player shops.
I checked the logs, but there where no errors. I also checked the save.yml file, which was perfectly fine, which left me perplex. Even restarting the server and reloading the plugin had no effect on the apparently frozen yml file and non spawning shops.
So I tried adding a new villager, and once I did, then the file got reset.

Now I'll just apply a backup of both the affected world and the save file (It's no big deal honestly). It does worry me that it may happen again very soon though.

Possible solution for future issues: Maybe you should consider implementing mysql as a data storage option. I'm sure it's been said many times, but this is the only solution I can come up with.

Shopkeepers version: 1.82
No errors. Plugin loads fine.

**Comment by blablubbabc** [comment]
MySQL will probably just bring a different batch of issues.
For the next update there are some loading/saving related changes planned already, maybe those help:
https://github.com/Shopkeepers/Shopkeepers/commit/f1db58437bcea032c8c42ff1348f890470257eb4
https://github.com/Shopkeepers/Shopkeepers/commit/5be3923a18f59918bf8571f023f1ba0457d85055

Especially: This should fix a rare race condition during plugin disable, if the data is currently getting saved async and the plugin disable triggers another sync save at the same time. And it waits for ongoing async tasks before continuing disable, maybe this helps on restarts.

However, your described problem seems to be related to loading mostly (save.yml exists with correct data, but doesn't get loaded properly):
If it detects some issue there, you should either get a severe message from bukkit, a stack trace from shopkeepers or a warning by shopkeepers (depending on the underlying issue). Could you check your logs again if there are really no errors/warnings at all? If there are no stacktraces, and you were using 1.82, maybe search your logs especially for the messages appearing in this code section: https://github.com/Shopkeepers/Shopkeepers/blob/40813ba93768d38cf9a4b80449ce758458ee2806/src/main/java/com/nisovin/shopkeepers/ShopkeepersPlugin.java#L1173-L1280
And it should print warnings in case the shops couldn't be loaded at chunk loads.

**Comment by blablubbabc** [comment]
Also forgot to ask, but if you by chance still have the save file for which this can be reproduced, that would be helpful of course.

**Comment by MithrandirCraft** [comment]
Well this has happened a few times in the 3-4 years I've been using your plugin. I wouldn't call it a common event.
I'll send you the current file through bukkit. However, I'd say pretty much anithing could be sparking this issue. It's thousands of lines of save data...

**Comment by blablubbabc** [comment]
The save file you sent me loads fine for me, so I can't really do anything about this issue right now.

The plugin already catches issues during loading of the save.yml file and then disables the plugin in order for the save data to not get lost. And it should at least print a stack trace if there is an unexpected error during loading of the individual shopkeepers, and in 1.84 it now catches any unexpected error there as well. So that in case the issue is related to loading a specific shopkeeper it should in the future disable the plugin instead of continuing and the potentially overwriting the save data later.

Edit: Actually, I just found a bug with the loading: Did your save.yml file by chance get larger than 1024kb in the past? I just tested with a massive amount of empty shopkeepers (10000) which yields a save file of ~2000kb, and Shopkeepers will then only load the first ~5000 of those shopkeepers, corresponding to the first 1024kb of the save file.
