### ISSUE TITLE
Option to disable "Remove shop" button for hired Shopkeepers.

### ISSUE THREAD

**Issue by wasder** [Shopkeepers/Shopkeepers#491]
We have a private area where players can hire shopkeepers predefined by admin. Some players by accident removes their hired shopkeeper in the chest gui. We need to disable this for players.

**Comment by blablubbabc** [comment]
There is currently no real support for 'predefined shops' yet. The current 'shopkeeper hiring' feature is really a 'shopkeeper selling' feature (maybe I should rename it). So removing the 'Remove shop' button is no option, because the shop belongs to the player and he should be able to remove his own shops again.

The correct way to support 'presetup rentable shops' would be to have a different command for admins which spawns an rentable shop belonging to the server, and for the remove button to turn the shop back into its 'rentable' state.

There is another ticket open about 'rentable shops', so I will close this one as duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/3

Though I don't see this happening any time soon yet.

The closest you can get currently is by setting up regions with WorldGuard inside your shop area, aassigning them the 'allow-shop' flag, disable building, but make sure that they can still interact and access chests, and enable enable-world-guard-restrictions and disable the 'require chest recently placed'-setting in the config.
And then only place pre-setup chests (players can't build there) and let the players setup their shops themselves there in those predefined areas, using those pre-setup chests.
