### ISSUE TITLE
Invalid object type for shopkeeper...

### ISSUE THREAD

**Issue by FatherWh0** [Shopkeepers/Shopkeepers#506]
Trying to update from 1.86 to 2.2.0 I'm getting an error on several species of shopkeeper. 

https://hastebin.com/raw/jagorafefu

Config before update: https://pastebin.com/pTzVL0B8
I did remove all msg entries from config before updating.
server log during update: https://pastebin.com/xFxUhCjq
Config after update: https://pastebin.com/19qvfTKW

As you can see the entries are present in the config file for the species types shopkeepers is failing to load. 

I deleted the config.yml allowing shopkeepers to generate a fresh one but it resulted in the same errors.
latest log creating fresh config: https://pastebin.com/rnwy3zku

paper 1.12.2 # 1474

**Comment by blablubbabc** [comment]
Some change in the last update has also slightly affected the ids the shopkeeper object gets saved/loaded with. This should be fixed in v2.2.1, by being able to load (and convert) the previous ids. Please let me know if that is the case.

Also I noticed that you are using lower case entity type names in your config: I don't think Shopkeepers has been able to load these previously and instead silently ignored them.. The update also includes some validation and better matching of those entity type names, so those should work fine in the next version.
