### ISSUE TITLE
help magmaCub 

### ISSUE THREAD

**Issue by stiruzo** [Shopkeepers/Shopkeepers#540]
Shopkeepers version:  2.2.2

Spigot version: 1.11.2

Hello, I created a shop with the shape of a Magma Cub but he himself grew up and then become a child. How stabilized at a certain age?

**Comment by blablubbabc** [comment]
I think the magma cube (and any other mob) might currently randomly spawn as either child or adult whenever it gets respawned. There is no way currently to persist or edit whether the mob is a child or adult.

Before support for something like this could be added I will first have to separate the mob properties into a separate inventory menu (see https://github.com/Shopkeepers/Shopkeepers/issues/10, which already mentions child variants of mobs as feature, so I will close this as duplicate).

Alternatively you could probably also you the integration with citizens and spawn a child citizens npc and use that as shopkeeper. See the wiki on the Citizens integration.

For the time being (until proper support for selecting and persisting the baby-state of mobs) I set all spawned mobs to adult now, so that it at least dosn't randomly spawn baby variants anymore.

**Comment by stiruzo** [comment]
ok thank you, suddenly you will make an update for the mob keeps his adult size by default?

**Comment by blablubbabc** [comment]
This will be part of the next update. No ETA on that yet though.

**Comment by stiruzo** [comment]
ok, I look forward to it;) thank you
