### ISSUE TITLE
After update to 1.13 most trades show red X

### ISSUE THREAD

**Issue by FatherWh0** [Shopkeepers/Shopkeepers#553]
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.6.0
* **Spigot version:** `Paper 1.13.2 566`
---

## The issue:

After updating to 1.13 enchanted item trades and potion trades show up with red X and cannot be traded. The editing screen doesn't remove the items. 
Also, old trades of items that no longer exist show up as red X and cannot be removed.

This does not reproduce on a new, fresh server. This issue is from updating an existing server.

This is from the log on the initial boot to 1.13: https://pastebin.com/GjTDWJrX

**Comment by blablubbabc** [comment]
Your log doesn't show anything unusual (except that you seem to be importing from a pre 2.3.x version (?), but that shouldn't be a problem).

In version 2.6.0 I added the ability to setup more than 8 trades per shopkeeper and I keep displaying out-of-stock trades in the editor and the trading menu (with red X), until they are explictly removed, regardless of if the chest contains the required items.
Are you sure this issue is specific to items with enchantments/potions, or is this a coincidence?

"and cannot be removed"

You should be able to remove trades for trades from the editor menu. For the selling player shopkeeper this can be done by decreasing the price to 0. Is this working?

"This issue is from updating an existing server."

Can you provide me the save data for one of the shopkeepers in question?

**Comment by FatherWh0** [comment]
Your info has helped me straighten this out. I was incorrect that I could not delete the trades. Sry, it was late and I misunderstood what I was seeing. Thanks for the help.
