### ISSUE TITLE
StackableItems incompatible with editor menu: Trade type shopkeepers sometimes 'steal' trade item in editing menu

### ISSUE THREAD

**Issue by FatherWh0** [Shopkeepers/Shopkeepers#554]
Shopkeepers version: `Shopkeepers-2.6.0
Spigot version: Paper 1.13.2 566

---

About much of the time when setting up a trade the item I place in the editing menu is removed from my inventory. Basically to set up to trade diamond blocks for a bow costs me my diamond block. These are player trade type shopkeepers.

Example: https://gyazo.com/34e3f5b506f778852a3ba2d093fa9196

**Comment by blablubbabc** [comment]
I am not able to reproduce this. Are you able to reproduce this on a fresh server without other plugins?

What other plugins are you running? Are there any plugins among those that might interfer with packet sending or inventory interactions (eg. ViaVersion, etc.)?

Are those items actually lost, or only visually (i.e. if you reconnect, are the items still missing)?

**Comment by FatherWh0** [comment]
It occurs with existing shopkeepers.

None of the other plugins should be interfering with inventories.

The items are actually lost, not just invisible.

It is odd that when the item is lost it shows up in the editing window as 2 items. When the normal, expected behavior occurs (item isn't lost) it shows up as one as expected.

**Comment by FatherWh0** [comment]
The conflict is with StackableItems. I opened a ticket there and the dev of that plugin asked that you check the EventPriority to be sure it's not set to highest.

Reference: https://github.com/haveric/StackableItems/issues/135

**Comment by blablubbabc** [comment]
I don't remember the details anymore, but it seems like these priorities were purposely set to highest at some point to prevent incompatibilities with other plugin(s): https://github.com/Shopkeepers/Shopkeepers/commit/5c31d009b746cfd0b8f545430244c12e36b89b6a

I will have to check if this can be changed.

In the past there have been cases in which Shopkeepers makes assumption about the outcome of the inventory click event after having processed it (and not cancelled). Basically relying on minecraft to process the inventory click as normal. So if some other plugin (like StackableItems) cancels the event or modifies the involved items afterwards, these assumption might no longer hold leading to inconsistent results. I will have to check whether this is still the case (there have been some changes to inventory handling since then).

Also, I haven't checked yet how StackableItems works in details, but I am not sure yet if Shopkeepers can even deal correctly with custom item stack sizes. For example, Shopkeepers will make use of the max stack sizes defined by Bukkit's Material. If StackableItems doesn't somehow (this is probably tricky and dangerously.. if even possible at all) overwrite this, then Shopkeepers might produce incompatible results (items of oversized stacks getting lost, or items getting stacked higher than anticipated by StackableItems).

**Comment by haveric** [comment]
Just dropping in to note that I made a lot of assumptions in my response over on StackableItems. My main assumption is that Shopkeeper's handling of inventories should always take priority over/before StackableItems at least with respect to shop inventories. (Basically, StackableItems shouldn't stack shop items as then we'll both just be fighting over what is there in the slot)

**Comment by FatherWh0** [comment]
"... I am not sure yet if Shopkeepers can even deal correctly with custom item stack sizes."
It wouldn't be difficult to tell players to be sure the item they use while editing is a single item and not stacked. This should prevent shopkeepers from having to deal with superstacked items.

**Comment by blablubbabc** [comment]
> My main assumption is that Shopkeeper's handling of inventories should always take priority over/before StackableItems at least with respect to shop inventories.

If this incompatibility is limited to Shopkeepers 'editor menu' (a regular inventory), then this might work. I will however have to fundamentally (sounds more drastically than it probably is) change how Shopkeepers handles inventory clicks, because currently it handles inventory clicks generically the same (single inventory listener at highest priority that forwards the click event to the currently open 'UI') for all types of custom inventories (editor (regular chest inventory), trading (villager merchant inventory), etc.) and for some of these (the trading inventory) the highest priority is required for the same reason as to why StackableItems requires it: Making sure that no trades are processed (=applying exchanged items to the shop's stock in an associated chest) if some plugin has cancelled the trading by cancelling the corresponding inventory click event.

**Comment by blablubbabc** [comment]
I did some experimenting with changing the event priority for the editor inventory interaction events: https://github.com/Shopkeepers/Shopkeepers/commit/4e04946db02c1855f90dac30c84fd393de4c7e77
A compiled build of this is available here for experimenting: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.6.1-SI-compat-SNAPSHOT/Shopkeepers-2.6.1-SI-compat-20190626.211343-1.jar

This seems to work quite well already in my basic testing. Unfortunely, it seems like StackableItems is currently not ignoring cancelled InventoryDragEvents (https://github.com/haveric/StackableItems/blob/master/mods/bukkit/src/main/java/haveric/stackableItems/listeners/SIPlayerListener.java#L459), so this still doesn't work.

**Comment by FatherWh0** [comment]
What mc version is this build compatible with? I'm currently running 1.13.2.

**Comment by blablubbabc** [comment]
Yes, I have been testing with 1.13.2 as well. StackableItems doesn't work on 1.14.x

**Comment by haveric** [comment]
Just released an update to StackableItems (v1.0.6) that now cancels events properly.

**Comment by blablubbabc** [comment]
@haveric 
Seems to work fine in my very basic testing. Thanks!
