### ISSUE TITLE
Shopkeepers 1.14.2 jar

### ISSUE THREAD

**Issue by hurrgurl** [Shopkeepers/Shopkeepers#568]
Sorry for being a little bit offtopic here.

I'm having trouble compiling your latest shopkeepers.

Could you please post a jar somewhere?

http://nexus3.cube-nation.de/repository/snapshots/ is 404 right now.

**Comment by blablubbabc** [comment]
The maven repository has changed to https://nexus.lichtspiele.org/

Regarding compiling: I encountered no issues, so you have to be more precise (eg. maven log, errors, ..) so that I can look into those issues.

> Could you please post a jar somewhere?

The jar is also available at dev.bukkit.org: https://dev.bukkit.org/projects/shopkeepers/files
It took curse staff a while to approce the upload, hence the delay between my 'update is out'-message and the file showing up.
