### ISSUE TITLE
User Trade

### ISSUE THREAD

**Issue by creci** [Shopkeepers/Shopkeepers#570]
## Preliminaries:

* **Shopkeepers version:** `2.7.1`
* **Spigot version:** `1.14.2`
---
When you add a book to the trade and make a restart, he does not see it and adds it again as a new item.

**Comment by blablubbabc** [comment]
> When you add a book to the trade and make a restart, he does not see it and adds it again as a new item.

Can you be more precise please, maybe add a few screenshots for clarification.
My current interpretation: You are using a book shopkeeper, added a written book to the chest and setup the costs in the editor menu, and after the restart it treats the book as a new book and requires setup of the trade again / does not match the previous setup trade.

My guess what might be happening here is that maybe your book item is containing "irregular" data that Spigot normalizes either when the item gets saved and loaded inside the chest, or when it gets saved and loaded as part of the Shopkeeper trades. Resulting in the book item in the chest no longer matching the book item that is part of the setup trading recipe.

In that case I need detailed instructions on how you create this book item, so that I can try to reproduce the issue and see if I can find the problem with your book item.
