### ISSUE TITLE
Weird chest item transfers and dupe glitch

### ISSUE THREAD

**Issue by CargoDankster** [Shopkeepers/Shopkeepers#580]
## Preliminaries:

* **Shopkeepers version:** 2.7.2
* **Spigot version:** Paper 124
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was able to reproduce my issue on a freshly setup and up-to-date Paper Spigot server, 124 with the latest version of Shopkeepers, 2.7.2.

## The issue:

When moving any items between chests and player inventories, you will need to click twice to place the item into an inventory. Sometimes as well, picking an item up from your inventory will leave an identical copy where you picked it up from, causing it to dupe.

**Comment by blablubbabc** [comment]
* Please try to reproduce your issue on an up-to-date Spigot server. Paper has some internal differences which makes it harder for me to determine whether this is a plugin, paper, spigot or possibly even minecraft issue.
* Shopkeepers should not be handling player <-> chest inventory item transfers in any way. So maybe some other plugin is interfering. Test without other plugins.
* Make sure that you have no client mods installed. Those can interfer as well.
* If by 'chest' you mean the shopkeeper editor inventory, then you need to clarify which type of shopkeeper you are using, what slots you are clicking and what the observed behavior is.
* For further clarification, maybe make a short video showcasing your issue.

In the end I need to be able to determine the step-by-step instructions, from shopkeeper creation up to which slots to click and how to 'click' them (double click, shift clicking, dragging, etc.) in order to reproduce the issue on a fresh and up-to-date Spigot server.

**Comment by blablubbabc** [comment]
Were you able to resolve the issue? If yes, would you mind sharing what you did to resolve it, in case others run into the same issue?

**Comment by CargoDankster** [comment]
Issue with another plugin, AuctionHouse
