### ISSUE TITLE
shopkeeper not spawning with villager egg

### ISSUE THREAD

**Issue by MAXERMANER** [Shopkeepers/Shopkeepers#590]
## Preliminaries:

* **Shopkeepers version:** `<Version 2.2.2 >`
* **Spigot version:** `<Spigot 1.8.8>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

When right clicking with the villager egg I could not make a player shop in survival. Player shops do not seem to work, but admin shops work. MY server is using AntiXRay 1.8.6, Citizens, EssentialsX 2.17, Modifyworld, multirequest 1.1.3, permisssionsex 1.23.4, shopkeepers 2.2.2, simple-prefix, vault, and world edit 6.1.3. Spigot Version 1.8.8. Do I need to update shop keeper for my spigot version as well?

**Comment by blablubbabc** [comment]
The default config created by Shopkeepers v2.2.2 is aimed at MC 1.12. Since MC 1.8 still used data values to differentiate between the different mob eggs, you will have to make some adaptation: In order for the villager egg to be considered the shop creation item, change the 'shop-creation-item-data' in the default config from 0 to 120. Or change it to -1 to let it work with any mob spawn egg.
