### ISSUE TITLE
High performance

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#605]
Spigot-Ver: CraftBukkit version git-Spigot-ea7e48b-660b6d1 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

Shopkeeper-Ver:Shopkeepers-2.7.2.jar

Is there a problem with the latest MC version? Because the shopkeepers now consume almost 5% power what was not before

![shopkeeper](https://user-images.githubusercontent.com/35557302/62812120-b2784300-bb04-11e9-9e4c-67c5d990f5c5.png)

**Comment by blablubbabc** [comment]
These 2.42ms per tick are spent ensuring that hoppers/droppers/etc. don't move items into or out of protected chests. You seem to have 102 item movements per tick. Maybe check if you have excessive amounts of hoppers/droppers/-carts/etc. loaded in your world(s) and if you can reduce those.

I currently see no way for me to further improve this check..
I could do some experiements with caching results of these checks, but right now I don't expect this to make a difference..

**Comment by HolographicWings** [comment]
what tool do you using for see your server performances ?

> Spigot-Ver: CraftBukkit version git-Spigot-ea7e48b-660b6d1 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
> 
> Shopkeeper-Ver:Shopkeepers-2.7.2.jar
> 
> Is there a problem with the latest MC version? Because the shopkeepers now consume almost 5% power what was not before
> 
> ![shopkeeper](https://user-images.githubusercontent.com/35557302/62812120-b2784300-bb04-11e9-9e4c-67c5d990f5c5.png)

what tool do you use for see your sever performances ?

**Comment by Blueeyestar** [comment]
I with /timings paste

**Comment by HolographicWings** [comment]
thanks you

**Comment by blablubbabc** [comment]
Okay, I think I actually found a small change that resulted in a major performance improvement for this.
I built some large hopper contraption, as well as a dropper contraption that gets constantly activated by redstone clocks (http://prntscr.com/ovgnv7).
Timings before the changes: https://timings.spigotmc.org/?url=qexiyowoca
Timings after the changes: https://timings.spigotmc.org/?url=aveqosozol

Some things to notice in these timings reports:
* Ignore the high 'server load'. I had many programs open at the same time there.
* WorldGuard spends a lot of time handling those item movements as well (even more than Shopkeepers apparently). So it is nevertheless important to try to avoid constantly running contraptions that cause large amounts of item movements between inventories / blocks (hoppers, dropper chains, etc.).
* The timings for handling the InventoryMoveItemEvent went down from **1.88 ms per tick to 0.06 ms**.
* There are over 2400 block physics updates per tick due to the constantly running redstone clocks in my contraption. I was also able to _slightly_ improve the performance for handling this event, but I don't think there is much more room for further improvements there. If this is an issue, either avoid redstone clocks / anything that causes constant block physics updates, or disable sign shops in the config.

**Comment by blablubbabc** [comment]
Should be fixed/improved in v2.8.0

**Comment by Blueeyestar** [comment]
Thank you :)

**Comment by blablubbabc** [comment]
Consider posting another timings report. Would be really interested in how much of a difference this has made for you!

**Comment by Blueeyestar** [comment]
**Unfortunately I cannot download the file** https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.8.0-SNAPSHOT/Shopkeepers-2.8.0-20190821.083957-11.jar **the page is offline**

**Comment by blablubbabc** [comment]
The file should also be available over at dev.bukkit.org now.
The maven repository is not hosted/maintained by myself, so I don't know when it will be available again.

**Comment by Blueeyestar** [comment]
With the newest version 2.8.0 Shopkeeper is really stable and in the timings there are no more high values. Super work !!!
![shopkee](https://user-images.githubusercontent.com/35557302/63689914-8c90b500-c80b-11e9-8a6c-59e2f35ea1fa.png)

**Comment by blablubbabc** [comment]
To be fair, your PerTick value for the InventoryMoveItemEvent has reduced from the original 102 to 1 in this newer timings report. A more interesting comparison would have been with the original ~100 inventory item movements per tick ;)

Also make sure to update to 2.8.1 which includes a hotfix for another issue related to player shops.
