### ISSUE TITLE
Incompatibility with Fast Async WorldEdit

### ISSUE THREAD

**Issue by HolographicWings** [Shopkeepers/Shopkeepers#608]
Hello
the plugin Fast Async WorldEdit is a fork of World edit who add the flag : allow-shop for worldguard
https://www.spigotmc.org/resources/fast-async-worldedit-voxelsniper.13932/
it's the same of Shopkeeper, so these two plugins are incompatible
can you change the name of the flag please ?
crash log of the worldguard plugin (line 165) : http://haste.athion.net/onirucojup.md

1.14 version of async world edit : https://ci.athion.net/job/FastAsyncWorldEdit-1.14/
compatible version of worldguard for async world edit : https://dev.bukkit.org/projects/worldguard/files/2663455/download

**Comment by blablubbabc** [comment]
Can you link me to the code of AsyncWorldEdit registering this flag? I don't seem to be able to find it via code search in their repository.

However, there should be no issue with multiple plugins trying to register this flag, if those plugins are doing it correctly. The purpose is to have a single flag which is the same across all shop plugins. Otherwise server admins would have to use a specific flag for each shop plugin, and there would be no way for some other plugin to determine if some region is a 'shop region' without being aware of all the individual shop region flags of all the different shop plugins existing..

Regarding registering the flag correctly:
Shopkeepers for example catches the exception resulting from WorldGuard if the flag is already registered. Checking if the flag is already registered would work as well.
ChestShop for example is doing it this way as well: https://github.com/ChestShop-authors/ChestShop-3/blob/master/src/main/java/com/Acrobot/ChestShop/Plugins/WorldGuardFlags.java
So there should be no issue with those two plugins running side by side.

My current guess regarding your issue is that you are using an outdated version of WorldGuard: WorldGuard registered this flag itself in the past, but they removed it some time ago and left it to plugins to register it (since it doesn't use it itself).
So if you are using an older version of WorldGuard, and some other plugin such as Shopkeepers has already registered the flag, then WorldGuard itself will fail to register the flag.

You seem to be using a build from january. The flag got removed from WorldGuard in March.
You can find the latest dev builds of WolrdGuard here: http://builds.enginehub.org/job/worldguard

**Comment by HolographicWings** [comment]
i have send a message to the dev of AsyncWorldEdit if they have a way for a fix, because their plugin need a specific version of worldguard

**Comment by blablubbabc** [comment]
I moved the config loading into the onLoad phase of the plugin and added a config setting 'register-world-guard-allow-shop-flag'. Note that changing this setting has no effect until the next server restart or full server reload.

A snapshot for testing this is available here: https://nexus.lichtspiele.org/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.8.0-SNAPSHOT/Shopkeepers-2.8.0-20190819.232314-10.jar
(The website seems to be having some ssl certificate issue currently though)

**Comment by blablubbabc** [comment]
Fixed in v2.8.0
