### ISSUE TITLE
Item desepear when we define trade

### ISSUE THREAD

**Issue by BlackFox3000** [Shopkeepers/Shopkeepers#642]
## Preliminaries:

* **Shopkeepers version:** `2.9.2`
* **Spigot version:** This server is running Paper version git-Paper-143 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **` able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **` Paper version git-Paper-143`**) with the latest version of Shopkeepers (currently **`2.9.2`**)
## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
When we create a new trade into a shopkeppeur. 
The moment where we select a item, we select one or a stack and when we click into the case for define this item top sell or buy, us hand was clear.

**Comment by BlackFox3000** [comment]
sorry it s my first issu  ^^'

**Comment by blablubbabc** [comment]
Maybe some other plugin is interfering.
Can you try to:
* Try in on a Spigot server instead of Paper. Paper has some internal differences. Trying it on a fresh and up-to-date Spigot server ensures that these are not the problem here.
* Try it without other plugins. If it works then (which I assume..), try to figure out which other plugin is causing this by adding them step by step. Also, please post your plugins list.

**Comment by BlackFox3000** [comment]
Plugins | Paper on 1.15.2-R0.1-SNAPSHOT: RecompensesVote 1.0; LuckPerms 5.0.104; WorldEdit 7.1.0,8e55131; EntityTrackerFixer 1.2.2; BlockLocker 1.7.2; AutoMessage 2.5.5; WorldBorder 1.9.10 (beta); Votifier 2.6.0-SNAPSHOT; ProtocolLib 4.5.0; Multiverse-Core 4.1.0-b775; WorldGuard 7.0.2-SNAPSHOT,bf2593e; BungeeGuard 1.0-SNAPSHOT; BlocksHub 3.1.1; GSit [2.10.1.0]; Multiverse-Portals 4.1.0-b805; Vault 1.7.2-b107; SimplePortals 1.4.5; CoreProtect 2.18.2; Essentials 2.17.2.3; PerWorldInventory 2.3.1; HolographicDisplays 2.4.1; SmoothSleep 2.8.1; Citizens 2.0.26-SNAPSHOT (build 1852); Shopkeepers 2.9.2; MythicMobs 4.9.0-3255; EssentialsChat 2.17.2.3; SuperbVote 0.5.4; Multiverse-NetherPortals 4.1.0-b763; EssentialsSpawn 2.17.2.3; BungeeTabListPlus 3.0.10; WorldGuardExtraFlags 4.1.3; Denizen 1.1.3-SNAPSHOT (build 1704-REL); BeautyQuests 0.16.1
-- | --

**Comment by BlackFox3000** [comment]
Okay i try to create a new serveur ^^'  for test

**Comment by BlackFox3000** [comment]
The problem not come to the plugins .. with spigot only he work

**Comment by BlackFox3000** [comment]
I can't reproduce the same error. On my server , my player can create personalize trade, but in spigot only, i can only trade with emerald ._. ...

**Comment by blablubbabc** [comment]
> The problem not come to the plugins .. with spigot only he work

I am not completely sure I understand: Were you able to confirm that the issue is some other plugin interfering? If that is the case, the next step is to find out which plugin is causing the issue.
What you can do to speed up the search instead of trying one plugin after the other: Add half of the other plugins back. If the issue occurs, remove half of those plugins and so on. If the issue does not occur, try with the other hald of the plugins.

> I can't reproduce the same error. On my server , my player can create personalize trade, but in spigot only, i can only trade with emerald ._. ...

You might be using different shop types on your server then. There are: Admins shops, selling shops, buying shops, book shops and trading shops. The selling, buying and book shops use emeralds as currency. The trading and admin shops can trade any items.

**Comment by BlackFox3000** [comment]
Okay, after long research, the bug comes from the RecompenseVote. A plugin created by a old player who have quit the team  few days ago .. bad luck for us ^^' 

The plugin:
https://github.com/la-taverne-mc/RecompensesVote

More than found the problem in this plugin...but  if you know the solution i take it!  x'D 
Thank you for you help ! Sorry for the lost time ^^"

**Comment by blablubbabc** [comment]
Glad you figured out which plugin was causing this!

**Comment by BlackFox3000** [comment]
Hi, thank you for your help, i worked this 3 days to edit a plungin and  Now i can edit, and create the .jar ! xD

I wondered if it existed an function to a InventoryClickEvent that can test if an inventory of shopkeepers?

**Comment by blablubbabc** [comment]
You could check if the inventory is instanceof MerchantInventory (this applies to regular villager trading menus as well though).

**Comment by BlackFox3000** [comment]
Thank you very much, i have solved the bug! ☺
