### ISSUE TITLE
Currencies, Villager Level, and Gringotts - I need some guidance, please!

### ISSUE THREAD

**Issue by roracle** [Shopkeepers/Shopkeepers#654]
* **Shopkeepers version: 2.9.3
* **Spigot version: git-Spigot-a99063f-fad2494 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
---
I was unable to find in the wiki what I'm looking for, and though this is an issue thread for lack of finding a regular discussion I decided to post here instead.

I don't understand currencies.  It's rather confusing.  So I'll explain how my server is set up economically:

I use Gringotts with values set this way (notice iron nuggets are worthless:
  denominations:
    - material: iron_ingot
      value: 0.01
    - material: iron_block
      value: 0.09
    - material: gold_nugget
      value: 0.81
    - material: gold_ingot
      value: 7.29
    - material: gold_block
      value: 65.61
    - material: diamond
      value: 590.49
    - material: diamond_block
      value: 5314.41

I wish for players to be able to trade using money only with the QuickShop plugin, but I also wish for players to barter which is where Shopkeepers comes in.

Is there a way to set it up where Shopkeepers trade virtual currency values, or must it be items?  If I can, I could get rid of QuickShop.  If not, well that's where I need to understand what you refer to as Currencies and Villager Levels are, as I'm assuming they have something in common though I can't seem to figure it out. The Wiki is very lacking in what Villager Levels are.

So please help me out here.  Like I said, two things:
1A. Can I trade virtual currency in Shopkeepers and if so how?
OR
1B. If not 1A, how do I ensure Shopkeepers are set to only barter?

and

2. An explanation of Villager Levels and their relationship to Currencies if any?

**Comment by blablubbabc** [comment]
> Is there a way to set it up where Shopkeepers trade virtual currency values, or must it be items?

Shopkeepers only supports item-based trades, no virtual currency.

>  I need to understand what you refer to as Currencies and Villager Levels are, as I'm assuming they have something in common though I can't seem to figure it out.

Villager levels have nothing to do with currencies and are simply a cosmetic property of the villager entity. See this image from the minecraft wiki: https://minecraft.gamepedia.com/File:Minecraft_villager_level_badges.png

> how do I ensure Shopkeepers are set to only barter?

I don't understand this question, sorry. Shopkeepers always 'only barter': They trade one or two input items for on output item. The currencies you specify inside the Shopkeepers config are simply a shortcut for setting up trades for these 'currency items' inside buying and selling shops. But in the end these trades are item-based as well.

**Comment by roracle** [comment]
I'm still not understanding Currencies, though.  I was hoping for more of an explanation.  Can I completely disable currencies since I have a virtual currency, or is there a more in-depth understanding I can garner from you regarding them?  Everything, as I said, is a bit lacking.  I've always been better with tools when I have a full rundown of their purpose and how they work.

**Comment by blablubbabc** [comment]
First of all (to make this clear in case there is confusion): The currency setup inside the Shopkeepers config has nothing to do with the currencies you have setup inside of Gingotts. The currencies you setup inside of the Gringotts config assigns each of these items a value in the virtual currency so that you/the Gringotts plugin can dynamically convert between these items and the virtual currency whenever some other plugin (eg. the QuickShop plugin) asks for a certain value of the virtual currency to be removed or added to some player.

The currency items ('low' and 'high') you setup inside the Shopkeepers config control the item types that appears inside the shop editor when you create and setup the trades for player shopkeepers of type 'selling' or type 'buying'. See for example the descriptions and images inside the wiki regarding the selling shopkeeper: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Player-Shop-Setup#selling-shop
You can click these emerald and emerald block items (labels 'Cost1' and 'Cost2') inside the editor to adjust the prices (i.e. how many of these items a trading player has to provide in order to get the result item of the trade).

There is never any conversion happening (at least not by the Shopkeepers plugin) between these shopkeeper currency items and your server's virtual currency.

**Comment by blablubbabc** [comment]
I assume this question to be resolved. If not, just let me know.
