### ISSUE TITLE
MythicMobs Items (any JSON text with RBG on items) trade support

### ISSUE THREAD

**Issue by Bodyash** [Shopkeepers/Shopkeepers#689]
Hello
There is some changes in MythicMobs items generation code

These items working fine with Shopkeeper until restart
I think it's because when I put some item to shopkeeper - object stored in memory
But when server is restarted - it should be loaded again.
And... item.Display name is changed also

First output - what I took from a shopkeeper after server restart
Second - what I put into originaly
![Screenshot from 2020-09-11 12-35-38](https://user-images.githubusercontent.com/2454569/92914670-1ff35300-f42c-11ea-9b3d-06c6eee12e15.png)

Okay, for example I can set MM to generate items with JSON name format, Like this
![Screenshot from 2020-09-11 12-43-55](https://user-images.githubusercontent.com/2454569/92915373-cb040c80-f42c-11ea-880b-e15968cc3c1e.png)
By simply using <#color> and <bold> tags instead of old &color &font format
But it's using as much tags as I put in config (bold, text color, etc..)

Example:
![Screenshot from 2020-09-11 12-45-17](https://user-images.githubusercontent.com/2454569/92915522-f1c24300-f42c-11ea-979f-318ff41c7f8f.png)
This is 2 outputs from same item with RGB gradient in name and bold font
The first one was taked from shopkeeper after restart
the second one is original item

So after restart Shopkeeper is adding all possible tags when generating item stack from save.yml, while MM adding only used tags. (like italic, underlined, etc..)

Paper 1.16.2 build 183

**Comment by blablubbabc** [comment]
Duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/578

The issue is that the item serialization API of Spigot (which the Shopkeepers plugin uses to save and load items to/from the save.yml) does not persist the Json data correctly currently: https://hub.spigotmc.org/jira/browse/SPIGOT-5063
The 'workaround' right now is to create the items originally with the internal Json data matching the format that is produced by Spigot (i.e. which you get in your 'after restart' case).
