### ISSUE TITLE
I CAN'T REMOVE VILLAGERS

### ISSUE THREAD

**Issue by 133434543** [Shopkeepers/Shopkeepers#698]
I CAN'T REMOVE VILLAGERS WHAT I NEED TO DO NOW!!!

VERSION: CB 1.7.9-R0.2

**Comment by blablubbabc** [comment]
Can you clarify your issue? Are you talking about regular villagers or shopkeeper villagers? The plugin should not interfere with regular villagers at all.

How are you trying to 'remove villagers'? You can remove shopkeeper villagers via the editor option in the shopkeeper editor.
If the editor is not working, the issue might be an incompatibility with either another plugin or your server (eg. some modded servers don't work well with Shopkeepers). Also, client side mods can interfer as well so make sure that those are not the issue.

Since you are using a very old version of CB, which version of Shopkeepers are you using? Make sure that you are using a compatible version of shopkeepers. I think the latest version supporting CB 1.7.9 is v1.68 (https://dev.bukkit.org/projects/shopkeepers/files/905923)

From the given information alone I am only able to randomly guess what the issue might be. If what I have written does not help you resolve the issue, I will require additional information on what you are trying to do and what exactly is not working (in a form so that I can reproduce your issue on my testing server) .

**Comment by 133434543** [comment]
ohh in gui ok thx
