### ISSUE TITLE
I can't buy

### ISSUE THREAD

**Issue by 133434543** [Shopkeepers/Shopkeepers#699]
Shopkeeper Version: 1.68
Spigot Version: I have Thermos

I want to test Villgaer and when im clicking anything then trade gui is closing

**Comment by blablubbabc** [comment]
Modded servers other than CB / Spigot are not supported.
However, in the past I was able to resolve this specific issue by disabling a minor check inside the code. See https://github.com/Shopkeepers/Shopkeepers/issues/538

Since Thermos seems to be a variant of Cauldron and the described issues seems to match the issue if the linked ticket, check if the linked version of shopkeepers works for you as well. If it does not, you are out of luck.

**Comment by 133434543** [comment]
works thx
