### ISSUE TITLE
[Feature Request] Default NPC Type setting on config file 

### ISSUE THREAD

**Issue by joex92** [Shopkeepers/Shopkeepers#710]
a setting for the default NPC Shopkeeper Type to fix an issue with Citizens plugin in Offline-mode servers.

Suggested setting name: `default-npc-type`

**Comment by blablubbabc** [comment]
Additional notes:
* Player npc shopkeepers (npc type 'player', and name of the player) cannot be spawned, because the server (for some reason not yet clear reason) will use an uuid based on the npc's name, which matches and conflicts with the uuid of the player.
* Probably since: https://github.com/CitizensDev/Citizens2/commit/a944c3ca9c5058869129721a8eb640dbec09fdb7
* (Potential other issue: This commit seems to only set the uuid field of the entity, but there are other derived fields that do not get updated accordingly (eg. the string representation of the uuid is cached by the entity)
* It is not yet clear why the npc entity uses an uuid based on its name.
  - New NPC's use a random UUID: https://github.com/CitizensDev/Citizens2/blob/master/main/src/main/java/net/citizensnpcs/npc/CitizensNPCRegistry.java#L51
  - This UUID is then used for the GameProfile of the Player NPC: https://github.com/CitizensDev/Citizens2/blob/master/v1_16_R3/src/main/java/net/citizensnpcs/nms/v1_16_R3/entity/HumanController.java#L37
  - Which is passed to the underlying MC EntityHuman (https://github.com/CitizensDev/Citizens2/blob/master/v1_16_R3/src/main/java/net/citizensnpcs/nms/v1_16_R3/entity/EntityHumanNPC.java), which then should extract the uuid from the GameProfile. An offline uuid is only used if the profile does not provide an uuid.

**Comment by joex92** [comment]
CitizensDev/Citizens2#2404

**Comment by blablubbabc** [comment]
The next version comes with a setting 'default-citizen-npc-type' (default: 'PLAYER'), which should allow you to resolve this issue.

**Comment by joex92** [comment]
I believe it would be nice also if you could set a "default-npc-skin", where "player" is by default, that way you could set a default skin and all npc citizens would be created with a default skin, wouldn't still that work?

**Comment by blablubbabc** [comment]
Added in v2.13.0.

I created a separate ticket for the NPC skin suggestion: https://github.com/Shopkeepers/Shopkeepers/issues/745

**Comment by joex92** [comment]
omg that's great! thanks!
