### ISSUE TITLE
Nether lava walk

### ISSUE THREAD

**Issue by matahombres** [Shopkeepers/Shopkeepers#711]
## Preliminaries:

* **Shopkeepers version:** `2.12.0`
* **Spigot version:** `1.16.4 (Paper)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`1.16.4`**) with the latest version of Shopkeepers (currently **`2.12.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

Magma cube and strider no go up lava.
In minecraft normal looks like this:
https://i.gyazo.com/e4eee2447355024279332ed9f5fddb67.png

But with shopkeeper looks like this:
https://gyazo.com/07af536d2750da39ded742a558472553

**Comment by blablubbabc** [comment]
This will be improved in the next version (I will close this ticket once that is released).

Magma cubes and striders will be able to stand on top of lava, unless they are completely submerged by it (they won't glide to the top like they do in vanilla, but instead sink to the ground in this case).
There will also be some change in how the shopkeeper's initial spawn location is determined so that it is possible to place shopkeepers on top of liquids when using the command, but still place them on the target block when being inside of the liquid (eg. when being under water or fully inside of lava).

I will probably also allow blazes to stand on top of lava (even though they sink to the ground in vanilla Minecraft).

**Comment by blablubbabc** [comment]
Added in v2.13.0
