### ISSUE TITLE
~2% of server CPU spent only only your EnityDamageEvent handler?

### ISSUE THREAD

**Issue by BigScary** [Shopkeepers/Shopkeepers#715]
I reviewed your code on Github briefly and it seems to me you're going straight to looking for a metadata tag.  Maybe it would be more performant to check entity type against the list of types enabled to be shopkeepers first?

https://timings.aikar.co/?id=c5c144993dcd4720adcc115cda2a56c9

**Comment by blablubbabc** [comment]
I have already attempted some optimization for this on v2.11.0 (you seem to be using v2.10.0, latest is v2.12.0). I think to remember that this didn't make that much of a difference in my testing. However, since you seem to have a lot of damage events going on on your server, it would be interesting for me if you could test this (ideally with a comparable situation) with the latest version of Shopkeepers and provide me with a timings report of that.

**Comment by blablubbabc** [comment]
On the latest version (without more optimizations) this already seems to be far more performant: https://timings.spigotmc.org/?url=iqumuvuhat

I tried to replicate your situation with around ~20+ damage events per tick and only got 0.03% of tick time spent on this.

**Comment by blablubbabc** [comment]
Although I think that this has already been improved for the most part in v2.11.0, I was able to further improve the performance of this (and several other things) in v2.13.0. I therefore consider this issue to be resolved.
