### ISSUE TITLE
[Feature Request] Per shop player blacklisting

### ISSUE THREAD

**Issue by impmallet** [Shopkeepers/Shopkeepers#727]
Hello,

Perhaps this is not common, but I run into issues on my server where players like to try to destroy the market by buying out all other shops and then reselling their goods at a lower price. Normally I would call this free market, but I get so many complaints about it that it would be nice for each player to block certain other players from using their shops.

I understand if this is not a highly desirable feature, but if you think it could be a good idea and that others would also benefit from it, it would be nice if you would consider adding it. This could also be used with Admin shops to prevent certain players from trading (for whatever reason, such as a punishment)

Thank you.

**Comment by blablubbabc** [comment]
> players like to try to destroy the market by buying out all other shops and then reselling their goods at a lower price

I have no clue about economic theory, but if they end up selling for a lower price, how is this an issue? Other sellers were still able to sell their goods to this single person for their intended price, and interested buyers can still get the items, even cheaper and more conveniently, from this single person. And as soon as the stock of that single person runs out again, the prices should normalize again. So all this creates is a brief bubble, with no loss for neither the original sellers nor the interested buyers.

Typically I would expect this single person to buy out the market to then resell the items at a higher price, in which case the original sellers could simply increase their prices (since apparently there is the demand for it, even though it is coming all from that single person). As long as new items steadily enter the market by other means, this should only be a brief interruption for other interested buysers, limited by the capital that single person is willing to spend.

Anyways, I don't have an opinion on this yet (the second scenario sounds more of an issue to me compared to the first one). However, there seems to already exist a ticket for this 'issue', so I will close this as duplicate: https://github.com/Shopkeepers/Shopkeepers/issues/650

The idea / request there has been to set up some kinds of  limit of how many items can be bought by a single player. But your idea of a general player blacklist would certainly be easier to add. However, I am not really convinced yet that this would actually solve the 'issue': These players could hire other players to buy these items for them. And there will also always be new players that follow this scheme.

Regarding restricting access to admin shops: You can already achieve this by assigning the admin shopkeeper an arbitrary permission node (command `setTradePerm`). With a permission plugin you could, for example, setup a default value for this permission, and then negate it for particular players to prevent them from accessing the particular admin shopkeeper.

Similarly, you could also already setup a system that blocks the players that cause undesired market disturbances by (temporarily) revoking their general `shopkeeper.trade` permission: They can then no longer trade with any shopkeepers. Via an addon plugin that hooks into the shopkeeper trade events, you could even automate this by logging player trades and then either automatically triggerthis punishment or notify you whenever a player buys a lot of the same items in a short period of time.

**Comment by impmallet** [comment]
Thanks for the reply. It's not a perfect solution, but the way I see shopkeepers is almost like chests that can be locked. It would be nice if player could be able to limit who can interact with their things, even if it's for an arbitrary reason. Just additional customization for those who want it.

Again, thank you for taking the time to reply and considering my request.
