### ISSUE TITLE
Ignore shulker box color and NBT tag 

### ISSUE THREAD

**Issue by LynSisCZ** [Shopkeepers/Shopkeepers#729]
Ignore on trading shop color and NBT tag on shulker box 

![image](https://user-images.githubusercontent.com/7085389/113964523-f1a3ed80-982b-11eb-99a5-a1e1fbcbdb06.png)
![image](https://user-images.githubusercontent.com/7085389/113964541-f8cafb80-982b-11eb-85e5-e59beb2c7d9a.png)

![image](https://user-images.githubusercontent.com/7085389/113964530-f5d00b00-982b-11eb-96d6-ca1a77105e6a.png)

**Comment by blablubbabc** [comment]
See the section on shulker boxes in the wiki's 'known issues': https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues
Basically, Minecraft inserts NBT data when you place and pickup a shulker box. This picked up shulker box will then no longer match a newly created shulker box. This is not something I can change.
If you want the trade to ignore the NBT data, you need to use a shulker box without the NBT data when you setup the trade. This trade will then accept shulker boxes both with or without the NBT data

Shopkeepers adheres to Minecraft's trading / item comparison logic. Since differently colored shulker boxes are different types of items, they are not considered equivalent in regards to trading.
