### ISSUE TITLE
Shopkeeper Crash in the Console

### ISSUE THREAD

**Issue by Blueeyestar** [Shopkeepers/Shopkeepers#736]
We have had this error message every time we restart for a short time.
Isn't Shopkeeper clear with the new paper version?

Paper-Version Paper version git-Paper-652 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

Shopkeeper: Shopkeepers-2.12.0.jar

`>.... [16:49:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A - git-Paper-652 (MC: 1.16.5) ---
>.... [16:49:28 ERROR]: The server has not responded for 10 seconds! Creating thread dump
>.... [16:49:28 ERROR]: ------------------------------
>.... [16:49:28 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
>.... [16:49:28 ERROR]: ------------------------------
>.... [16:49:28 ERROR]: Current Thread: Server thread
>.... [16:49:28 ERROR]: PID: 17 | Suspended: false | Native: false | State: RUNNABLE
>.... [16:49:28 ERROR]: Stack:
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.IBlockAccess$$Lambda$5465/1033244659.apply(Unknown Source)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.IBlockAccess.a(IBlockAccess.java:144)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.IBlockAccess.rayTrace(IBlockAccess.java:85)
>.... [16:49:28 ERROR]: org.bukkit.craftbukkit.v1_16_R3.CraftWorld.rayTraceBlocks(CraftWorld.java:1371)
>.... [16:49:28 ERROR]: com.nisovin.shopkeepers.util.Utils.getCollisionDistanceToGround(Utils.java:277)
>.... [16:49:28 ERROR]: com.nisovin.shopkeepers.shopobjects.living.LivingEntityAI.lambda$start$0(LivingEntityAI.java:274)
>.... [16:49:28 ERROR]: com.nisovin.shopkeepers.shopobjects.living.LivingEntityAI$$Lambda$5473/2125679604.run(Unknown Source)
>.... [16:49:28 ERROR]: org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
>.... [16:49:28 ERROR]: org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1423)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:419)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1338)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1126)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
>.... [16:49:28 ERROR]: net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3074/2070333417.run(Unknown Source)
>.... [16:49:28 ERROR]: java.lang.Thread.run(Thread.java:748)
>.... [16:49:28 ERROR]: ------------------------------
>.... [16:49:28 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
>.... [16:49:28 ERROR]: ------------------------------`

**Comment by blablubbabc** [comment]
From the looks of it this seems to be a server-internal problem (probably raytracing continuing indefinitely for some reason). However, I cannot spot anything related to this in the recent paper changes. I also cannot reproduce this issue yet. So maybe this is caused by a specific shopkeeper that is located at a position that is somehow affected by this issue.

Since you mentioned that you can reliably reproduce this issue:
* Try to reproduce this issue on Spigot. Paper has done several changes to ray tracing, chunk loading, collision checks for certain blocks, .. in order to optimize these operations. If you can also reproduce this on Spigot then the issue has to be something Paper-unrelated.
* Try older Paper versions, versions that you know were not affected by this issue previously. If all paper versions are affected now, this might be an issue triggered by a particular shopkeeper that you/one of your players recently added. If not, then this maybe helps tracking down the paper change that caused this.
* Tryto track down the particular Shopkeeper / situation in which this occurs. Make a backup and then remove some of the recently added shopkeepers (those at the bottom of the save file) to see if one of those causes it. If you have no luck with this, I can also look into providing a shopkeeper version that logs shopkeeper ids whenever they are about to execute the code mentioned in the stack trace. If you can identify the shopkeeper in question, try to provide some background information about it that may help me to reproduce and then debug the issue, such as where it is located, if it is located near the spawn area, at the border of the spawn area, far out of the spawn area, your world's spawn location, what are the blocks around/below it, is it located in mid air, above the void, etc.

**Comment by blablubbabc** [comment]
Any news on this?
