### ISSUE TITLE
Citizens shopkeeper issue

### ISSUE THREAD

**Issue by EvilPandaMan** [Shopkeepers/Shopkeepers#754]
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.13.1.jar`
* **Spigot version:** `paper_1.17`
---

## The issue:

I understand that everything is in a transitional process, so I'm just dropping this here for awareness. All my citizens shopkeepers keep disappearing and it only prompt one little warn/error on console.

![Screenshot 2021-06-29 120506](https://user-images.githubusercontent.com/22263166/123787103-56725f80-d8d2-11eb-99f4-7aaee96e154d.png)

**Comment by EvilPandaMan** [comment]
Despite what it says (there are no npcs...) Previously I didn't have to create an npc beforehand, the npc shopkeeper would automatically create them.

**Comment by blablubbabc** [comment]
Are you using the latest Citizens build?

> keep disappearing

When exactly are they disappearing? Do they appear in-game when you spawn a new NPC shopkeeper? Do they disappear once your restart the server? If yes, maybe it's an issue with the NPC not getting saved to the Citizens save file for some reason (maybe I need to explicitly trigger a save now. Though, this wasn't required in the past if I remember correctly.).

**Comment by blablubbabc** [comment]
I have tested both on 1.16.5 and 1.17 and can not see a behavioral difference. However, one has to note that on both versions of Citizens and the Shopkeepers plugin, the shopkeeper Citizen NPCs are not saved to the Citizens saves files immediately, but rather on shutdown of the Citizens plugin. This is similar to when you manually create a new Citizens NPC and then not immediately invoke the `/citizen save` command.

The error message you get is new on v2.13.0+: It informs you about shopkeepers for which the corresponding Citizens NPC is not found. This can for example occur if the server crashes without Citizens performing its saves during shutdown. Or if you forcefully clear the Citizens saves file, or delete Citizens NPCs while the shopkeepers plugin is not running. But as far as I can tell, nothing has changed between 1.16.5 and 1.17 in regards to when Citizen NPC are saved or not saved, or deleted.

However, I could consider triggering an immediate Citizens save whenever a new Citizens shopkeeper is created.

**Comment by blablubbabc** [comment]
I cannot reproduce any issues with Citizens NPCs disappearing, unless the server crashes before Citizens was able to save the NPC data.

However, I added a new setting for the next version of shopkeepers: `save-citizen-npcs-instantly` (disabled by default) that triggers a save of the Citizens NPCs whenever the Shopkeeper plugins modifies a Citizens NPC.
Since there is no API yet to trigger an asynchronous save, I triggers these saves by executing the `/citizens save -a` command in the console. However, as a side effect, this will print command feedback messages to the console whenever the Citizens NPCs are saved this way.

Enabling this setting comes with a small performance hit whenever you create or edit a new Citizens shopkeeper, but should make it less likely to run into the warning message you posted.
