### ISSUE TITLE
[Request] Option to disable result item check

### ISSUE THREAD

**Issue by Rubenicos** [Shopkeepers/Shopkeepers#776]
## Description
Add the option to disable the safe-check in TradingHandler:
https://github.com/Shopkeepers/Shopkeepers/blob/52e83bb6a07db5415e293a0465c2b0af11c553aa/modules/main/src/main/java/com/nisovin/shopkeepers/ui/trading/TradingHandler.java#L546-L549

## Why
I get the error "Not handling trade: The trade result item does not match the expected item of the active trading recipe!" when i try to edit the trading recipes for client-side.

**Comment by blablubbabc** [comment]
This error indicates that you are not actually only modifying the item on the client side, but also on the server side. If you are modifying the outgoing merchant trade list packet, you need to copy the whole merchant recipe list, and all the merchant recipes you are trying to modify the items of. Otherwise your modifications also affect the actual merchant list on the server side.
