### ISSUE TITLE
GriefPreventionFlags issue

### ISSUE THREAD

**Issue by Lammendam** [Shopkeepers/Shopkeepers#788]
## Preliminaries:

* **Shopkeepers version:** `2.14.0`
* **Server version:** `Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

I use GriefPreventionFlags, for setting claim flags because I use GriefPrevention for land claims.
When i try to assign a chest to shop, i catch console issue ([issue log](https://www.pastebin.com/ZS3v0WTV)).
It's only appears in administrative claims (where is no owner) and it doesn't affect on player claims.
I suggest it's because administrative claims doesn't have owner name (it's null by GP).

Reproduce:
Install GP and GPFlags (www.spigotmc.org/resources/griefprevention-flags.55773/), create an administrative claim, put a chest in this claim, and assign it to the shop (via shop item).

**Comment by blablubbabc** [comment]
I am not sure how the Shopkeepers plugins is related to this, other than that you click the chest with an item in hand in order to select it for shop creation. But the stack trace seems to indicate that only GPFlags is involved in this error.

Try to reproduce this without the Shopkeepers plugin (e.g. do the same chest interaction, but without the Shopkeepers plugin running on the server). And then report this issue to the GPFlags developers.
