### ISSUE TITLE
bug in shopkeepers

### ISSUE THREAD

**Issue by ItsMuffin24** [Shopkeepers/Shopkeepers#790]
hello,
i had a bug with shopkeepers, in version of minecraft 1.18.2 the villagers of shopkeepers stuck and not look up the player. its strange. what i can do to fix it or you (the develper of plugin) need to out a patch for 1.18.2?

**Comment by blablubbabc** [comment]
Yes, I need to release an update for 1.18.2 to fix this issue. But so far I have not yet found the time for this because:
* I currently don't have much time to work on this project during the week.
* I had some work in progress that I wanted to complete first (this has been completed with the recent commits).
* I noticed that there are still some other (severe) issues with the current snapshot version of the plugin (i.e. the current code base) that I still need to resolve before I can release an update.

However, other than the shopkeepers not looking towards nearby players I am not aware of any issues currently.

**Comment by blablubbabc** [comment]
v1.15.1 with support for MC 1.18.2 has been released on dev.bukkit.org
