### ISSUE TITLE
Basic Player Commands don't work

### ISSUE THREAD

**Issue by BryanP88** [Shopkeepers/Shopkeepers#796]
## The issue:
The server is a 1.18.2 Paper server. There are no other Mods or Plugins except this one. The plugin doesn't work for any non-OP user even though it says in the Permissions documentation that players have access to "basic commands" out of the box. The players can't use /shopkeeper give to get the basic item which allows them to create a shop. And I don't have any permission plugins on the server which would interfere with this. Also the config.yml file has none of these permission options detailed in the documentation here: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions 

All the YouTube videos I watch on this plugin show that placing a chest down and then selecting the Spawn Item will give options. Mine doesn't do that. The plugin only responds to the help command. Which doesn't give me any answers. 

Also I used a command on the console to give myself the villager spawner egg by force. When I place a chest and then select the villager spawner egg I don't get the options that all the guides and YouTube videos show. It's just a normal villager spawner egg and clicking the ground spawns a normal villager, not a shopkeeper. 

Here's a video: https://youtu.be/su9-hUwLzhw

**Comment by blablubbabc** [comment]
The plugin tries to avoid that normal non-op players need to use commands for anything basic, such as setting up shops. The `/shopkeeper give` command is really not meant to be used by normal players. It is a utility command for admins, similar to Minecraft's give command. As mentioned here (https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Creating-Shops#shop-creation-item), the recommended way of giving players access to the shop creation item is to set up an admin shop that sells it.

If you really want, you can also allow players to use the command to create player shops: This needs to be enabled first inside the config.

https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Permissions documents the default permission values. By default, players only have access to the permissions with `default: true`. If you want to make changes to the default permissions of your players, you will need to use a permissions plugin.

The default shop creation item is a villager spawn egg with a green display name "Shopkeeper". The item in your video seems to be a normal villager spawn egg (with the default display name).

As admin (op), you can use the `/shopkeeper give` to give yourself the shop creation item in-game, and then setup an admin shopkeeper that sells copies of it.

**Comment by BryanP88** [comment]
Okay the part that confused me is where the Permission section says, "layers with OP rights have access to everything, and regular players have access to trading, basic commands, and creating basic player shops." Their own documentation states that players can use the player shops. But then it's not actually true and you need a permissions addon to control everything.

**Comment by blablubbabc** [comment]
> But then it's not actually true and you need a permissions addon to control everything.

Players don't need access to any commands to create shops, because they can use the shop creation item. How they get access to this item is up to you, but as mentioned above, selling it as part of an admin shopkeeper is a common approach.
This admin shop needs to be setup by an admin, which corresponds to a 'server operator' in a plain server without a permissions plugin. Server operators have access to the required commands by default, so there is no need to configure permissions for them either.

And even if you enable the "setup of players shops via commands" inside the config, you don't need to change anything on the permissions.

So unless you are not happy with these defaults, there is no need for a permissions plugin. This is what this sentence on the Permissions page was trying to point out.

Looking at the default command permissions that players have access to, the "`basic commands`" seems to only refer to the `list` command currently, which is the only exception currently to the goal of not requiring normal players to use commands. But the listing of shops is not really an essential part of the Shopkeepers plugin anyway.
