### ISSUE TITLE
ViaVersion Works With Shopkeepers | BUT! If inside of WorldGuard it seems to disconnect them.

### ISSUE THREAD

**Issue by Zhaaaaaaaaa** [Shopkeepers/Shopkeepers#804]
## Preliminaries:

* **Shopkeepers version:** `2.16.0`
* **Spigot version:** `Paper version git-Paper 387 (MC:1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git:df630a2 on ver/1.18.2)`
---

## **I READ THE KNOWN ISSUES - I'M AWARE OF THE DISCONNECT OF USERS WITH ViaVersion. YOU DID FIX THE ISSUE. But...**

If the NPC's are inside of WorldGuard they get the disconnect. That is all. **Just wanted to let you know. Sorry for breaking up the Template.**

I'm using Geyser, ViaVersion, Floodgate.

**Comment by blablubbabc** [comment]
I don't understand what this ticket is about. Can you clarify please?

Is this about another issue with ViaVersion? Or about clarifying the description of the ViaVersion issue inside the Known Issues page inside the wiki (the issue somehow only a affecting shopkeepers located in world guard regions)?

**Comment by Saanjuk** [comment]
Some details here:
https://discord.com/channels/606329645779910686/606332085308751892/995713227843436654
I Can rocord This for You, if You want

**Comment by blablubbabc** [comment]
This issue has already been reported here (https://github.com/Shopkeepers/Shopkeepers/issues/799) and here (https://github.com/Shopkeepers/Shopkeepers/issues/802).
So my question is what this ticket is about, and what WorldGuard has to do with this.

**Comment by Saanjuk** [comment]
Oh ... in my case WordGuard has nothing .. Sorry I thought it was identical issue to mine

**Comment by blablubbabc** [comment]
I have slightly updated the section in the "Known Issues" page inside the wiki, since it seems that there might be different ViaVersion related issues resulting in slightly different errors. However, the "Known Issues" page is not necessarily meant to document all issues in detail, but only to make aware of potential issues in relation with certain plugins. Hence the general note at the bottom, to try to reproduce issues without ViaVersion and any other network-related plugins.
So I think the current description + the existing tickets are sufficient.
