### ISSUE TITLE
" '{"extra":[{ " issue

### ISSUE THREAD

**Issue by CortezRomeo** [Shopkeepers/Shopkeepers#825]
## Preliminaries:

* **Shopkeepers version:** `2.16.4`**
* **Spigot version:** `This server is running Paper version git-Paper-794 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT`**
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

`          display-name: '{"italic":false,"color":"white","extra":[{"bold":true,"color":"yellow","text":"LÁ
            MÙA THU "},{"color":"green","text":"III"}],"text":""}'
          lore:
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"yellow","text":"Thông
            số:"}],"text":""}'
          - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"white","text":""}],"text":""}'
          - '{"extra":[{"italic":false,"color":"white","text":"Dùng để trao đổi các
            vật phẩm tại khu vực "},{"bold":true,"italic":false,"color":"light_purple","text":"Event"}],"text":""}'
          - '{"extra":[{"italic":false,"color":"white","text":"Được trao đổi tại "},{"italic":false,"color":"yellow","text":"/warp
            event"}],"text":""}'`
            
        
`          display-name: '{"italic":false,"color":"white","extra":[{"bold":true,"color":"yellow","text":"LÁ
            MÙA THU "},{"color":"green","text":"III"}],"text":""}'
          lore:
          - '{"italic":false,"color":"white","text":""}'
          - '{"italic":false,"color":"yellow","text":"Thông số:"}'
          - '{"italic":false,"color":"white","text":""}'
          - '{"italic":false,"color":"white","extra":[{"color":"white","text":"Dùng
            để trao đổi các vật phẩm tại khu vực "},{"bold":true,"color":"light_purple","text":"Event"}],"text":""}'
          - '{"italic":false,"color":"white","extra":[{"color":"white","text":"Được
            trao đổi tại "},{"color":"yellow","text":"/warp event"}],"text":""}'` 

These are similar item, but 1 of them has ` '{"extra":` at the beginning and it cause the item need to trade doesn't match.
How can I disable that check "extra" or do something to fix this problem?

**Comment by blablubbabc** [comment]
The plugin compares item data like how Minecraft itself compares the items in trades, and there are intentionally no options to change that (change to the comparison logic would result in client-side glitches).
The plugin also does not modify the text data of your items, but will store it as it was provided when you originally set up the trades.

So since the item inside the shopkeeper does no longer match the item you are currently trying to trade, my guess would be that something changed on how you create those items in the first place:
* Maybe the plugin you use to create the items changed something in an update.
* Some third plugin might dynamically modify the items on your server.
* In the past, there were cases in which server updates caused the text representation to change. But I am not aware of this being the case recently, at least on Spigot. I have no information on Paper or other server variants.

**Comment by blablubbabc** [comment]
Closing this as no further information was provided.
