### ISSUE TITLE
disappering

### ISSUE THREAD

**Issue by ItzMqthyx** [Shopkeepers/Shopkeepers#831]
my shopkeepers are sometimes invisible and I cant interact with them and when i tried to create new its saying "this place is already taken" or smt like that and I have to restart my server like 5 times until the shopkeepers are normal and when I create new shopkeepers then every shopkeepers disappear again :(

**Comment by blablubbabc** [comment]
This might be caused by a conflict with one of your other plugins: Maybe one of your other plugins is preventing the shopkeeper from spawning.

You can turn on debug mode inside the shopkeeper config, then go to some shopkeeper location in-game, reload, wait for 10 seconds, and then if the shopkeepers have not appeared, check the log and send me this snippet containing the reload and spawn attempts.

Also make sure that you are testing this on a fresh and up-to-date Spigot issue, to ensure that the issue is not caused by any issues related to chunk loading or chunk load events, which the plugin reacts to to spawn the shopkeepers.

**Comment by ItzMqthyx** [comment]
it worked!
