### ISSUE TITLE
1.20 unsupported

### ISSUE THREAD

**Issue by Leonardo-Fiori** [Shopkeepers/Shopkeepers#854]
Hey there, I am updating my server from an older version to 1.20, I picked this (now outdated) version due to lots of issues with custom coded plugins and older plugins

I haven't updated my server yet, I am just planning the update, downloading all the jars and taking notes on what needs to be reconfigured and what should work out of the box

I noticed that you entirely skipped 1.20 support and went for 1.20.1

Might I ask what issues did you encounter with 1.20 support? I am thinking about hiring a developer to fork Shopkeepers and add 1.20 support but any hint would be extremely useful!

**Comment by blablubbabc** [comment]
1.20 support was implemented and later removed again, see: https://github.com/Shopkeepers/Shopkeepers/commit/c677e5ecdebfe0f51359503dc3ee717e29e32662

I can't remember the details, but Spigot dropped support for building 1.20 (maybe because 1.20.1 was released shortly afterwards without any major differences): I you try to build Spigot 1.20 with the BuildTools it actually builds 1.20.1 instead. This broke the Github build pipeline for the Shopkeepers plugin. For simplicity, I therefore decided to remove the 1.20 support again.
