### ISSUE TITLE
where the sold item is not shown, but when you click on it, it works?

### ISSUE THREAD

**Issue by chinhdz1091** [Shopkeepers/Shopkeepers#899]
pls help me
![2024-07-16 (1)](https://github.com/user-attachments/assets/e3d20876-3f2a-4fe9-b622-7852c00dddac)
![2024-07-16 (2)](https://github.com/user-attachments/assets/0f063f0f-0e3a-43ed-9888-83ebbb806c0f)

**Comment by blablubbabc** [comment]
- Post your exact server version (including the build number) (`/version` output)
- Post your plugin list
- My guess is that maybe some other plugin is interferring. You need to figure out which plugin. Try to reproduce your issue on an up-to-date Spigot server without other plugins and without client-side mods. Then step-by step re-add other plugins until you can reproduce the issue.

**Comment by Mattsgeheim123** [comment]
I'm having the same issue, it occurs when connecting to a server which is hosted on a newer version like 1.21 and then joining through an older client such as 1.20.6 through viaversion + viabackwards. I brought this up with the core developer of viaversion/viabackwards and they claimed it's a visual bug caused by the shopkeepers plugin.

**Comment by blablubbabc** [comment]
> and they claimed it's a visual bug caused by the shopkeepers plugin.

I will not debug cross-version / protocol / ViaVersion related issues. Unless someone familiar with the issue can clarify the cause of the issue / propose a potential solution, I will not further investigate it.

**Comment by YuanYuanOwO** [comment]
From simple test:
I think it's a issue from [Eco](https://github.com/Auxilor/eco) plugin
