### ISSUE TITLE
Feature Request: Disable Move / Delete shop options for players

### ISSUE THREAD

**Issue by TsengFayt** [Shopkeepers/Shopkeepers#908]
## Preliminaries:

* **Shopkeepers version:** `2.22.3`
* **Spigot version:** `Paper version 1.21-123-master@0a1be9a (2024-07-31T02:57:35Z) (Implementing API version 1.21-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki). ✅
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions). ✅
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues). ✅
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question. ✅

## Feature Request:

I would like the ability to disable players' ability to use the `Move Shopkeeper` and `Delete Shop` options. 

The way we setup our SMP, is that only approved players get to open a shop. Currently, I have the plugin set to where players cannot create shops, but admins can instead create a shop and then transfer the ownership to specific players. If the shops are abandoned, we can then wipe the shop, and reassign it to another player. However, we don't want players to be able to move the shopkeeper from where we place it, nor do we want them to be able to delete the shop. Instead, we only want them to be able to clear their chest of payments/items and then ask an admin to delete it for them.

**Comment by blablubbabc** [comment]
I don't plan to add a setting or permission for the deletion of shopkeepers, since this should ideally not be required. The proper solution is to rework this "for hire" feature, or add a separate "renting feature", and then properly handle everything related to temporarily renting shops. This feature is tracked by https://github.com/Shopkeepers/Shopkeepers/issues/3

Since there is no timeline for this feature, as a workaround for the time-being:
* There is already a setting `enable-moving-of-player-shops`.
* The deletion can currently only be blocked via an add-on plugin that cancels the `PlayerDeleteShopkeeperEvent`.
