### ISSUE TITLE
save.yml error

### ISSUE THREAD

**Issue by Yazuki1108** [Shopkeepers/Shopkeepers#923]
I'm sorry, but the text may be hard to read because it uses translation.

I run two servers with MohistMC.

However, while one server is running, I cannot use the Shopkeepers plugin on the other server.

I think this is because the save.yml references are to the same folder, but is it possible to set the reference in the config? I also checked several github questions about this, but they didn't work on my server.

MohistMC 1.20.1 549

Shopkeepers 2.17.2
[message.txt](https://github.com/user-attachments/files/17450709/message.txt)

**Comment by blablubbabc** [comment]
Hey, a few points:
* Mohist is not supported. There have been other issues reported before by users trying to use Shopkeepers together with Mohist.
* According to the error, the plugins is not able to delete the save file (it needs to do this when saving changes), because some other program has the save file opened / locks it.
  You mention that you run two servers accessing the same plugin folder: I don't know currently if this could explain the issue, but you can easily check by temporarily testing with only a single server.
  However, either way, if you are running into issues with this setup, this is nothing the Shopkeepers plugin currently explicitly intends to support, i.e. I don't intend to invest time to check for solutions to support this scenario. So if you can confirm that accessing the same save file from two servers is causing issues, consider not sharing the save file.
